export { default as Dashboard } from './Dashboard'
export { default as Studies } from './Studies'
export { default as Patients } from './Patients'
export { default as Sites } from './Sites'
export { default as Alerts } from './Alerts'
export { default as Agents } from './Agents'
export { default as Conversational } from './Conversational'
export { default as Reports } from './Reports'

// New pages from frontend design spec
export { default as EDCMetrics } from './EDCMetrics'
export { default as DataQuality } from './DataQuality'
export { default as VisitManagement } from './VisitManagement'
export { default as LaboratoryData } from './LaboratoryData'
export { default as SafetyMonitoring } from './SafetyMonitoring'
export { default as MedDRACoding } from './MedDRACoding'
export { default as WHODrugCoding } from './WHODrugCoding'
export { default as FormsVerification } from './FormsVerification'
export { default as CRAActivity } from './CRAActivity'
