
name: 'clinical_dataflow'
version: '1.0.0'
config-version: 2

profile: 'clinical_dataflow'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  clinical_dataflow:
    staging:
      +materialized: view
    marts:
      +materialized: table
